version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: erick
      POSTGRES_PASSWORD: erick123
      POSTGRES_DB: prueba
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

      
  redis:
    image: redis
    container_name: redis_socket
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: python_backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://erick:erick123@prueba:5432/mydb
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app



  # frontend:
  #   build: ./frontend
  #   container_name: react_native_app
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - "19000:19000"   # Expo
  #     - "19001:19001"
  #     - "19002:19002"
  #   volumes:
  #     - ./frontend:/app
  #   stdin_open: true
  #   tty: true

volumes:
  postgres_data:
  pgadmin_data: