version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: erick
      POSTGRES_PASSWORD: erick123
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: python_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://erick:erick123@prueba:5432/mydb
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: react_native_app
    restart: always
    depends_on:
      - backend
    ports:
      - "19000:19000"   # Expo
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

volumes:
  postgres_data: